require('dotenv').config();
const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),path=require('path');
const {Pool}=require('pg'); const app=express(); const db=new Pool({connectionString:process.env.DATABASE_URL});
app.use(cors());app.use(express.json());app.use(express.static(path.join(__dirname,'..')));
const secret=process.env.JWT_SECRET;
function token(user){return jwt.sign({id:user.id,role:user.role},secret,{expiresIn:'8h'})}
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),secret);next()}catch{return res.status(401).json({message:'Authentication required'})}}
function role(...roles){return(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({message:'You do not have permission for this action'})}
function validRequest(x){return x.cropId&&Number(x.quantity)>0&&x.centerId&&x.preferredDate}
app.post('/api/auth/register',async(req,res,next)=>{try{let {name,email,phone,password,address,village,district,state}=req.body;if(!name||!email||!phone||!password||!address||!village||!district||!state)return res.status(400).json({message:'Please complete all required fields'});let hash=await bcrypt.hash(password,12);let r=await db.query('INSERT INTO users(name,email,phone,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,role',[name,email,phone,hash,'farmer']);await db.query('INSERT INTO farmers(user_id,address,village,district,state) VALUES($1,$2,$3,$4,$5)',[r.rows[0].id,address,village,district,state]);res.status(201).json({user:r.rows[0],token:token(r.rows[0])})}catch(e){if(e.code==='23505')return res.status(409).json({message:'An account already uses that email or phone'});next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{let r=await db.query('SELECT id,name,email,password_hash,role,status FROM users WHERE email=$1',[req.body.email]);let u=r.rows[0];if(!u||u.status!=='active'||!(await bcrypt.compare(req.body.password||'',u.password_hash)))return res.status(401).json({message:'Invalid email or password'});delete u.password_hash;res.json({user:u,token:token(u)})}catch(e){next(e)}});
app.get('/api/centers',auth,async(req,res,next)=>{try{res.json((await db.query('SELECT * FROM procurement_centers ORDER BY name')).rows)}catch(e){next(e)}});
app.get('/api/crops',auth,role('farmer'),async(req,res,next)=>{try{res.json((await db.query('SELECT c.* FROM crops c JOIN farmers f ON f.id=c.farmer_id WHERE f.user_id=$1',[req.user.id])).rows)}catch(e){next(e)}});
app.post('/api/crops',auth,role('farmer'),async(req,res,next)=>{try{let x=req.body;if(!x.cropName||!x.quantity||!x.unit||!x.harvestDate)return res.status(400).json({message:'Crop name, quantity, unit and harvest date are required'});let r=await db.query('INSERT INTO crops(farmer_id,crop_name,crop_variety,quantity,unit,harvest_date) SELECT id,$2,$3,$4,$5,$6 FROM farmers WHERE user_id=$1 RETURNING *',[req.user.id,x.cropName,x.cropVariety||null,x.quantity,x.unit,x.harvestDate]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
app.post('/api/requests',auth,role('farmer'),async(req,res,next)=>{const client=await db.connect();try{let x=req.body;if(!validRequest(x))return res.status(400).json({message:'Please provide crop, quantity, center and preferred date'});await client.query('BEGIN');let n=(await client.query("SELECT nextval('procurement_requests_id_seq') AS id")).rows[0].id, id=`ULV-${new Date().getFullYear()}-${String(n).padStart(5,'0')}`;let r=await client.query('INSERT INTO procurement_requests(procurement_id,farmer_id,crop_id,center_id,quantity,preferred_date,remarks) SELECT $1,f.id,$2,$3,$4,$5,$6 FROM farmers f JOIN crops c ON c.id=$2 AND c.farmer_id=f.id WHERE f.user_id=$7 RETURNING *',[id,x.cropId,x.centerId,x.quantity,x.preferredDate,x.remarks||null,req.user.id]);if(!r.rowCount)throw Object.assign(new Error('Crop not found'),{status:404});await client.query('INSERT INTO notifications(user_id,title,message) VALUES($1,$2,$3)',[req.user.id,'Procurement request submitted',`${id} is awaiting verification.`]);await client.query('COMMIT');res.status(201).json(r.rows[0])}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
app.patch('/api/requests/:id/official',auth,role('officer','admin'),async(req,res,next)=>{try{let x=req.body,sql=req.user.role==='admin'?'UPDATE procurement_requests SET status=$1,updated_at=now() WHERE id=$2 RETURNING *':'UPDATE procurement_requests SET status=$1,updated_at=now() WHERE id=$2 AND center_id=(SELECT center_id FROM officers WHERE user_id=$3) RETURNING *',args=req.user.role==='admin'?[x.status,req.params.id]:[x.status,req.params.id,req.user.id],r=await db.query(sql,args);if(!r.rowCount)return res.status(404).json({message:'Request not found or not assigned to your center'});res.json(r.rows[0])}catch(e){next(e)}});
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({message:err.status?err.message:'Something went wrong. Please try again.'})});
app.listen(process.env.PORT||4000,()=>console.log('ULAVAN API running'));
