-- PostgreSQL production schema for ULAVAN – THE FOODMAKER
CREATE TYPE user_role AS ENUM ('farmer','officer','admin');
CREATE TABLE users (id BIGSERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, phone VARCHAR(20) UNIQUE NOT NULL, password_hash TEXT NOT NULL, role user_role NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE procurement_centers (id BIGSERIAL PRIMARY KEY, name VARCHAR(160) NOT NULL, address TEXT NOT NULL, village VARCHAR(100), district VARCHAR(100) NOT NULL, state VARCHAR(100) NOT NULL, contact_number VARCHAR(20), operating_hours VARCHAR(100), daily_capacity NUMERIC(12,2) NOT NULL CHECK(daily_capacity > 0));
CREATE TABLE farmers (id BIGSERIAL PRIMARY KEY, user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE, address TEXT NOT NULL, village VARCHAR(100) NOT NULL, district VARCHAR(100) NOT NULL, state VARCHAR(100) NOT NULL);
CREATE TABLE officers (id BIGSERIAL PRIMARY KEY, user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE, center_id BIGINT REFERENCES procurement_centers(id));
CREATE TABLE crops (id BIGSERIAL PRIMARY KEY, farmer_id BIGINT NOT NULL REFERENCES farmers(id) ON DELETE CASCADE, crop_name VARCHAR(80) NOT NULL, crop_variety VARCHAR(80), quantity NUMERIC(12,2) NOT NULL CHECK(quantity > 0), unit VARCHAR(20) NOT NULL, harvest_date DATE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE procurement_requests (id BIGSERIAL PRIMARY KEY, procurement_id VARCHAR(30) UNIQUE NOT NULL, farmer_id BIGINT NOT NULL REFERENCES farmers(id), crop_id BIGINT NOT NULL REFERENCES crops(id), center_id BIGINT NOT NULL REFERENCES procurement_centers(id), quantity NUMERIC(12,2) NOT NULL CHECK(quantity > 0), preferred_date DATE NOT NULL, remarks TEXT, status VARCHAR(40) NOT NULL DEFAULT 'Request Submitted', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX procurement_requests_farmer_idx ON procurement_requests(farmer_id); CREATE INDEX procurement_requests_center_idx ON procurement_requests(center_id);
CREATE TABLE procurement_schedules (id BIGSERIAL PRIMARY KEY, request_id BIGINT UNIQUE NOT NULL REFERENCES procurement_requests(id) ON DELETE CASCADE, center_id BIGINT NOT NULL REFERENCES procurement_centers(id), procurement_date DATE NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, scheduled_by BIGINT NOT NULL REFERENCES officers(id));
CREATE TABLE procurement_records (id BIGSERIAL PRIMARY KEY, request_id BIGINT UNIQUE NOT NULL REFERENCES procurement_requests(id) ON DELETE CASCADE, accepted_quantity NUMERIC(12,2) CHECK(accepted_quantity >= 0), quality_status VARCHAR(30), quality_remarks TEXT, completion_date DATE, completed_by BIGINT REFERENCES officers(id));
CREATE TABLE payments (id BIGSERIAL PRIMARY KEY, request_id BIGINT UNIQUE NOT NULL REFERENCES procurement_requests(id) ON DELETE CASCADE, amount NUMERIC(14,2), payment_status VARCHAR(30) NOT NULL DEFAULT 'Payment Pending', payment_date DATE, payment_reference VARCHAR(100));
CREATE TABLE notifications (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, title VARCHAR(160) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE complaints (id BIGSERIAL PRIMARY KEY, farmer_id BIGINT NOT NULL REFERENCES farmers(id), request_id BIGINT REFERENCES procurement_requests(id), category VARCHAR(60) NOT NULL, description TEXT NOT NULL, response TEXT, status VARCHAR(30) NOT NULL DEFAULT 'Open', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE announcements (id BIGSERIAL PRIMARY KEY, title VARCHAR(160) NOT NULL, message TEXT NOT NULL, created_by BIGINT NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), expiry_date DATE);
